/**
 * 词根词缀内置数据表（路线 A：随仓库内置，纯前端拆解，离线可用）
 * 前缀 / 后缀 / 词根，释义以构词中的实际含义为准，中英对照
 */

export interface AffixEntry {
  form: string
  zh: string
  en: string
}

export interface RootEntry {
  root: string
  zh: string
  en: string
}

// ── 前缀 ──────────────────────────────────────────────
export const PREFIXES: AffixEntry[] = [
  { form: 'un', zh: '不；未；相反', en: 'not; opposite' },
  { form: 'im', zh: '不；无法', en: 'not; unable' },
  { form: 'in', zh: '不；无；进入', en: 'not; into' },
  { form: 'ir', zh: '不；无法', en: 'not; unable' },
  { form: 'dis', zh: '相反；去掉；不', en: 'apart; not' },
  { form: 're', zh: '再；重新；回', en: 'again; back' },
  { form: 'pre', zh: '预先；在前', en: 'before' },
  { form: 'post', zh: '在后；后来', en: 'after' },
  { form: 'mis', zh: '错误地；坏地', en: 'wrongly' },
  { form: 'over', zh: '过度；在上方', en: 'too much; above' },
  { form: 'bio', zh: '生命', en: 'life' },
  { form: 'hypo', zh: '在下方；假', en: 'under; below' },
  { form: 'geo', zh: '大地；地球', en: 'earth' },
  { form: 'hyper', zh: '超过；过度', en: 'over; beyond' },
  { form: 'under', zh: '在下；不足', en: 'below; lacking' },
  { form: 'fore', zh: '预先；在前', en: 'before' },
  { form: 'non', zh: '不；非', en: 'not; non-' },
  { form: 'anti', zh: '反对；防', en: 'against' },
  { form: 'inter', zh: '之间；相互', en: 'between' },
  { form: 'trans', zh: '跨越；转换', en: 'across' },
  { form: 'sub', zh: '下；低于；次', en: 'under; below' },
  { form: 'super', zh: '超；在上方', en: 'above' },
  { form: 'multi', zh: '多', en: 'many' },
  { form: 'poly', zh: '多', en: 'many' },
  { form: 'uni', zh: '单一', en: 'one; single' },
  { form: 'mono', zh: '单；单一', en: 'single' },
  { form: 'bi', zh: '双；二', en: 'two' },
  { form: 'tri', zh: '三；三重', en: 'three' },
  { form: 'semi', zh: '半', en: 'half' },
  { form: 'hemi', zh: '半', en: 'half' },
  { form: 'omni', zh: '全；到处', en: 'all; every' },
  { form: 'pan', zh: '全；泛', en: 'all' },
  { form: 'com', zh: '共同；加强', en: 'together' },
  { form: 'co', zh: '共同；合作', en: 'together' },
  { form: 'con', zh: '共同；加强', en: 'together' },
  { form: 'sym', zh: '共同；相同', en: 'together' },
  { form: 'ex', zh: '出；前；完全', en: 'out; former' },
  { form: 'de', zh: '去除；下；相反', en: 'remove; down' },
  { form: 'out', zh: '超过；在外', en: 'beyond' },
  { form: 'en', zh: '使进入；使成为', en: 'cause to be' },
]

// ── 后缀 ──────────────────────────────────────────────
export const SUFFIXES: AffixEntry[] = [
  { form: 'ed', zh: '过去式', en: 'past tense' },
  { form: 'ing', zh: '现在分词；进行', en: 'present participle' },
  { form: 'ly', zh: '…地（副词）', en: 'adverb' },
  { form: 'ful', zh: '充满；具有…性', en: 'full of' },
  { form: 'less', zh: '无；没有', en: 'without' },
  { form: 'able', zh: '能够…；可…', en: 'able to' },
  { form: 'ible', zh: '能够…的', en: 'able to be' },
  { form: 'al', zh: '与…有关的', en: 'relating to' },
  { form: 'ous', zh: '充满；有…性质', en: 'full of' },
  { form: 'ive', zh: '有…性质的；倾向', en: 'inclining to' },
  { form: 'ic', zh: '…的；与…有关', en: 'of; relating to' },
  { form: 'ical', zh: '与…有关的', en: 'relating to' },
  { form: 'er', zh: '做…的人；工具', en: 'one who; device' },
  { form: 'or', zh: '做…的人或物', en: 'one that' },
  { form: 'ist', zh: '从事…的人', en: 'one who' },
  { form: 'ant', zh: '做…的（人/物）', en: 'doing' },
  { form: 'ent', zh: '做…的（人/物）', en: 'doing' },
  { form: 'tion', zh: '行为；结果；状态', en: 'action; state' },
  { form: 'sion', zh: '行为；状态', en: 'action; state' },
  { form: 'ment', zh: '行为；结果；工具', en: 'act; result' },
  { form: 'ness', zh: '性质；状态；程度', en: 'state; quality' },
  { form: 'ize', zh: '使成为；…化', en: 'to make' },
  { form: 'ise', zh: '使成为；…化', en: 'to make' },
  { form: 'ify', zh: '使成为；…化', en: 'to make' },
  { form: 'ate', zh: '使…；进行…', en: 'to cause' },
  { form: 'ence', zh: '性质；状态', en: 'state; quality' },
  { form: 'ance', zh: '性质；状态', en: 'state; quality' },
  { form: 'ity', zh: '性质；状态；程度', en: 'state; degree' },
  { form: 'ure', zh: '行为；结果', en: 'act; result' },
  { form: 'ism', zh: '制度；主义；行为', en: 'system; doctrine' },
  { form: 'ory', zh: '场所；性质（名词）', en: 'place; state' },
  { form: 'log', zh: '学科；记录', en: 'study; record' },
  { form: 'logy', zh: '…学；…的学科', en: 'study of' },
  { form: 'ish', zh: '像…；有…倾向', en: 'like; tending to' },
  { form: 'es', zh: '复数', en: 'plural' },
  { form: 's', zh: '复数', en: 'plural' },
]

// ── 词根 ──────────────────────────────────────────────
export const ROOTS: RootEntry[] = [
  { root: 'spect', zh: '看；观', en: 'look; see' },
  { root: 'spec', zh: '看', en: 'look' },
  { root: 'volu', zh: '转；滚', en: 'turn; roll' },
  { root: 'lect', zh: '选择；收集', en: 'choose; gather' },
  { root: 'pend', zh: '悬挂；支付', en: 'hang; pay' },
  { root: 'stand', zh: '站立；忍受', en: 'stand; endure' },
  { root: 'form', zh: '形状；形成', en: 'shape; form' },
  { root: 'vis', zh: '看', en: 'see' },
  { root: 'cur', zh: '跑；追求', en: 'run; seek' },
  { root: 'benef', zh: '利益；好处', en: 'benefit' },
  { root: 'chrom', zh: '颜色', en: 'color' },
  { root: 'satisf', zh: '满足；使满意', en: 'satisfy' },
  { root: 'duc', zh: '引导；导致', en: 'lead' },
  { root: 'duct', zh: '引导', en: 'lead' },
  { root: 'scrib', zh: '写；画', en: 'write; draw' },
  { root: 'script', zh: '写；画', en: 'write' },
  { root: 'dict', zh: '说；断言', en: 'say' },
  { root: 'dic', zh: '说', en: 'say' },
  { root: 'port', zh: '拿；运送；支持', en: 'carry; bring' },
  { root: 'ject', zh: '投掷；扔', en: 'throw' },
  { root: 'struct', zh: '建造', en: 'build' },
  { root: 'tract', zh: '拉；拖', en: 'pull' },
  { root: 'cap', zh: '抓；拿；头', en: 'seize; head' },
  { root: 'capt', zh: '抓；拿；头', en: 'seize; head' },
  { root: 'cept', zh: '拿；取；接受', en: 'take; accept' },
  { root: 'ten', zh: '持；握', en: 'hold' },
  { root: 'tain', zh: '保持；坚持', en: 'hold' },
  { root: 'mit', zh: '送；派', en: 'send' },
  { root: 'mis', zh: '送；派', en: 'send' },
  { root: 'aud', zh: '听；看', en: 'hear; see' },
  { root: 'grad', zh: '走；等级；步', en: 'step; degree' },
  { root: 'log', zh: '言；学说', en: 'word; study' },
  { root: 'phil', zh: '爱；喜欢', en: 'love' },
  { root: 'creat', zh: '创造', en: 'create' },
  { root: 'cre', zh: '创造；生长', en: 'create; grow' },
  { root: 'cent', zh: '一百；中心', en: 'hundred; center' },
  { root: 'mer', zh: '仁慈；交易', en: 'kindness; trade' },
  { root: 'mor', zh: '伦理；习惯', en: 'custom; ethics' },
  { root: 'viv', zh: '活；生命', en: 'life; live' },
  { root: 'vit', zh: '生命', en: 'life' },
  { root: 'ann', zh: '年', en: 'year' },
  { root: 'lun', zh: '月亮；情绪', en: 'moon; moods' },
  { root: 'sol', zh: '太阳；粘合', en: 'sun; glue' },
  { root: 'terr', zh: '土地；恐惧', en: 'earth; fear' },
  { root: 'aqua', zh: '水', en: 'water' },
  { root: 'ign', zh: '火；燃烧', en: 'fire' },
  { root: 'pet', zh: '寻求；脚', en: 'seek; foot' },
  { root: 'fug', zh: '逃；跑', en: 'flee; run' },
  { root: 'ced', zh: '走；退', en: 'go; yield' },
  { root: 'ceed', zh: '走；前进', en: 'go forward' },
  { root: 'curr', zh: '跑；流动', en: 'run; flow' },
  { root: 'ver', zh: '真实；词', en: 'true; word' },
  { root: 'pon', zh: '放；置', en: 'put; place' },
  { root: 'pos', zh: '放置；坐', en: 'put; sit' },
  { root: 'forgiv', zh: '原谅；宽恕', en: 'forgive' },
  { root: 'forg', zh: '原谅', en: 'forgive' },
  { root: 'leg', zh: '法律；送', en: 'law; send' },
  { root: 'rot', zh: '轮；转动', en: 'turn; wheel' },
  { root: 'gen', zh: '产生；族；性', en: 'produce; race' },
  { root: 'gen', zh: '产生；造', en: 'produce; make' },
  { root: 'nom', zh: '名字', en: 'name' },
  { root: 'nomen', zh: '名字', en: 'name' },
  { root: 'phon', zh: '声音', en: 'sound' },
  { root: 'graph', zh: '写；画；形', en: 'write; draw; shape' },
  { root: 'geo', zh: '大地；地球', en: 'earth' },
  { root: 'bio', zh: '生命', en: 'life' },
  { root: 'psych', zh: '心灵；精神', en: 'mind; spirit' },
  { root: 'psych', zh: '心理；精神', en: 'mind' },
  { root: 'graph', zh: '写；形；记录', en: 'write; form; record' },
  { root: 'chron', zh: '时间', en: 'time' },
  { root: 'path', zh: '疾病；感受', en: 'disease; feeling' },
  { root: 'path', zh: '路；疾病', en: 'way; disease' },
]
